import { createFileRoute } from '@tanstack/react-router'
import { ArrowRight, CircleAlert, Cloud, Database, ExternalLink, HardDrive, LockKeyhole, Radio, RefreshCw, ShieldCheck, Sparkles, Unplug, Waves } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'

export const Route = createFileRoute('/destinations')({ component: DestinationsPage })

function ProviderLogo({ provider }: { provider: string }) {
  if (provider === 'Spotify') return <span className="provider-logo spotify"><Waves /></span>
  if (provider === 'Deezer') return <span className="provider-logo deezer"><span><i /><i /><i /><i /></span></span>
  if (provider === 'Broadcast') return <span className="provider-logo broadcast"><Radio /></span>
  return <span className="provider-logo r2"><Cloud /></span>
}

function DestinationsPage() {
  return <div className="destinations-page page-enter">
    <section className="page-heading compact"><div><Badge variant="iris" className="mb-3"><Unplug className="size-3" />Capability-aware delivery</Badge><h1>One sound. Every destination.</h1><p>Cadessa prepares each schedule for a dedicated adapter—respecting what every provider, territory and license allows before delivery is enabled.</p></div><Button disabled>Cloud access required</Button></section>
    <section className="connection-overview"><Card><span className="overview-icon coral"><CircleAlert /></span><div><strong>0 of 4</strong><p>External destinations connected</p></div></Card><Card><span className="overview-icon iris"><RefreshCw /></span><div><strong>Never</strong><p>Last external publish</p></div></Card><Card><span className="overview-icon aqua"><ShieldCheck /></span><div><strong>60</strong><p>Metadata-ready titles</p></div></Card><Card><span className="overview-icon coral"><CircleAlert /></span><div><strong>60</strong><p>Licensed masters needed</p></div></Card></section>
    <section className="destination-grid">
      <Card className="destination-card"><CardHeader><ProviderLogo provider="Broadcast" /><Badge variant="coral"><CircleAlert className="size-3" />Needs audio</Badge></CardHeader><CardContent><h3>Pulse 96.5 playout</h3><p>Schedule exports work now. On-air delivery remains locked until licensed R2 masters and a playout endpoint exist.</p><div className="destination-facts"><span><small>Last delivery</small><strong>Never</strong></span><span><small>Available now</small><strong>CSV · JSON · M3U</strong></span></div><div className="delivery-line"><i /><span /><span /><span /><b /></div><div className="destination-actions"><Button asChild variant="secondary" size="sm"><a href="/api/studio/pulse-965?format=csv">Download CSV</a></Button><Button variant="ghost" size="sm" disabled>Awaiting endpoint</Button></div></CardContent></Card>
      <Card className="destination-card"><CardHeader><ProviderLogo provider="Spotify" /><Badge variant="coral"><CircleAlert className="size-3" />Not connected</Badge></CardHeader><CardContent><h3>Spotify playlist</h3><p>No account or playlist is connected. Cadessa will not invent provider IDs or imply a publish.</p><div className="destination-facts"><span><small>Last publish</small><strong>Never</strong></span><span><small>Playlist</small><strong>Not selected</strong></span></div><div className="provider-note"><LockKeyhole />Streaming content remains provider-isolated and is never sent to AI.</div><div className="destination-actions"><Button size="sm" disabled>OAuth access required</Button><Button variant="ghost" size="sm" disabled>View playlist <ExternalLink className="size-3" /></Button></div></CardContent></Card>
      <Card className="destination-card"><CardHeader><ProviderLogo provider="Deezer" /><Badge variant="coral"><CircleAlert className="size-3" />Needs access</Badge></CardHeader><CardContent><h3>Deezer playlist</h3><p>No account or playlist is connected. Connect credentials to discover the application’s granted capabilities.</p><div className="destination-facts"><span><small>Last publish</small><strong>Never</strong></span><span><small>Capability</small><strong>Unknown until OAuth</strong></span></div><div className="provider-note warm"><Sparkles />Cadessa will adapt to the permissions your Deezer application exposes.</div><div className="destination-actions"><Button size="sm" disabled>OAuth access required</Button><Button variant="ghost" size="sm" disabled>Learn more</Button></div></CardContent></Card>
      <Card className="destination-card"><CardHeader><ProviderLogo provider="R2" /><Badge variant="coral"><CircleAlert className="size-3" />Not provisioned</Badge></CardHeader><CardContent><h3>Owned audio vault</h3><p>The R2 binding is configured as code, but no cloud bucket or owned master has been supplied.</p><div className="destination-facts"><span><small>Assets</small><strong>0 masters</strong></span><span><small>Storage</small><strong>Awaiting Cloudflare access</strong></span></div><div className="storage-meter"><span><i style={{ width: '0%' }} /></span><small>0 bytes connected</small></div><div className="destination-actions"><Button size="sm" disabled>Cloudflare access required</Button><Button variant="ghost" size="sm" disabled>Browse assets</Button></div></CardContent></Card>
    </section>
    <Card className="architecture-strip"><div className="architecture-copy"><Badge variant="neutral">Built for provenance</Badge><h2>The right music goes to the right place.</h2><p>Provider references, owned audio and AI-safe editorial context stay in separate lanes. Conductor schedules from explicit capabilities—not assumptions.</p><Button asChild variant="ghost" size="sm"><a href="/introduction#architecture">Review data boundaries <ArrowRight className="size-3.5" /></a></Button></div><div className="architecture-flow"><span><Database /><small>Catalog</small></span><i /><span><Sparkles /><small>Conductor</small></span><i /><div><span><Radio /><small>Broadcast</small></span><span><Waves /><small>Playlists</small></span><span><HardDrive /><small>Exports</small></span></div></div></Card>
  </div>
}
