/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ClocksRouteImport } from './routes/clocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScheduleRouteImport } from './routes/api.schedule'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiStudioChannelIdRouteImport } from './routes/api.studio.$channelId'
import { Route as ApiGenerationChannelIdRouteImport } from './routes/api.generation.$channelId'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClocksRoute = ClocksRouteImport.update({
  id: '/clocks',
  path: '/clocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleRoute = ApiScheduleRouteImport.update({
  id: '/api/schedule',
  path: '/api/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioChannelIdRoute = ApiStudioChannelIdRouteImport.update({
  id: '/api/studio/$channelId',
  path: '/api/studio/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationChannelIdRoute = ApiGenerationChannelIdRouteImport.update({
  id: '/api/generation/$channelId',
  path: '/api/generation/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clocks': typeof ClocksRoute
  '/destinations': typeof DestinationsRoute
  '/insights': typeof InsightsRoute
  '/introduction': typeof IntroductionRoute
  '/library': typeof LibraryRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schedule': typeof ApiScheduleRoute
  '/api/generation/$channelId': typeof ApiGenerationChannelIdRoute
  '/api/studio/$channelId': typeof ApiStudioChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clocks': typeof ClocksRoute
  '/destinations': typeof DestinationsRoute
  '/insights': typeof InsightsRoute
  '/introduction': typeof IntroductionRoute
  '/library': typeof LibraryRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schedule': typeof ApiScheduleRoute
  '/api/generation/$channelId': typeof ApiGenerationChannelIdRoute
  '/api/studio/$channelId': typeof ApiStudioChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clocks': typeof ClocksRoute
  '/destinations': typeof DestinationsRoute
  '/insights': typeof InsightsRoute
  '/introduction': typeof IntroductionRoute
  '/library': typeof LibraryRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schedule': typeof ApiScheduleRoute
  '/api/generation/$channelId': typeof ApiGenerationChannelIdRoute
  '/api/studio/$channelId': typeof ApiStudioChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clocks'
    | '/destinations'
    | '/insights'
    | '/introduction'
    | '/library'
    | '/api/health'
    | '/api/schedule'
    | '/api/generation/$channelId'
    | '/api/studio/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clocks'
    | '/destinations'
    | '/insights'
    | '/introduction'
    | '/library'
    | '/api/health'
    | '/api/schedule'
    | '/api/generation/$channelId'
    | '/api/studio/$channelId'
  id:
    | '__root__'
    | '/'
    | '/clocks'
    | '/destinations'
    | '/insights'
    | '/introduction'
    | '/library'
    | '/api/health'
    | '/api/schedule'
    | '/api/generation/$channelId'
    | '/api/studio/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClocksRoute: typeof ClocksRoute
  DestinationsRoute: typeof DestinationsRoute
  InsightsRoute: typeof InsightsRoute
  IntroductionRoute: typeof IntroductionRoute
  LibraryRoute: typeof LibraryRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiScheduleRoute: typeof ApiScheduleRoute
  ApiGenerationChannelIdRoute: typeof ApiGenerationChannelIdRoute
  ApiStudioChannelIdRoute: typeof ApiStudioChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clocks': {
      id: '/clocks'
      path: '/clocks'
      fullPath: '/clocks'
      preLoaderRoute: typeof ClocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule': {
      id: '/api/schedule'
      path: '/api/schedule'
      fullPath: '/api/schedule'
      preLoaderRoute: typeof ApiScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio/$channelId': {
      id: '/api/studio/$channelId'
      path: '/api/studio/$channelId'
      fullPath: '/api/studio/$channelId'
      preLoaderRoute: typeof ApiStudioChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/$channelId': {
      id: '/api/generation/$channelId'
      path: '/api/generation/$channelId'
      fullPath: '/api/generation/$channelId'
      preLoaderRoute: typeof ApiGenerationChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClocksRoute: ClocksRoute,
  DestinationsRoute: DestinationsRoute,
  InsightsRoute: InsightsRoute,
  IntroductionRoute: IntroductionRoute,
  LibraryRoute: LibraryRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiScheduleRoute: ApiScheduleRoute,
  ApiGenerationChannelIdRoute: ApiGenerationChannelIdRoute,
  ApiStudioChannelIdRoute: ApiStudioChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
